# enable zmk studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=120000
CONFIG_BT_TX_POWER=-4
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_KSCAN_POLLING_INTERVAL=10
